from nicegui import ui
from ui.components.lucide import lucide_icon
from ui.components.header import create_header


import auth


def create_terms_page(from_page: str = None):
    """Renders the LexMesh Terms & Conditions page. Publicly accessible, no auth required."""

    # Determine caller context (Login, Audit, or Dashboard)
    if not from_page:
        from_page = "login" if not auth.get_current_user() else "dashboard"
    from_page = from_page.lower().strip()

    if from_page == "login":
        back_label = "Back to Login"
        back_url = "/login"
    elif from_page == "audit":
        back_label = "Back to Audit"
        back_url = "/audit"
    else:
        back_label = "Back to Dashboard"
        back_url = "/dashboard"

    ui.colors(
        primary='#4e795d',
        secondary='#eae3d2',
        positive='#3b6349',
        negative='#9e3232',
    )

    create_header()

    with ui.column().classes("w-full min-h-screen items-center py-10 px-4").style(
        "background: var(--lex-bg, #f5f2eb);"
    ):
        # ── Header ──────────────────────────────────────────────────────────
        with ui.column().classes("w-full max-w-3xl gap-2 mb-10"):
            with ui.row().classes("items-center gap-3"):
                with ui.element("div").style(
                    "width:48px;height:48px;border-radius:14px;"
                    "background:linear-gradient(135deg,#4e795d,#23382b);"
                    "display:flex;align-items:center;justify-content:center;"
                    "box-shadow:0 4px 16px rgba(78,121,93,0.35);"
                ):
                    lucide_icon("scale", size=26, class_name="", extra_style="color:#eae3d2;")

                with ui.column().classes("gap-0"):
                    ui.label("Terms & Conditions").style(
                        "font-size:2rem;font-weight:900;color:#1b3825;line-height:1.1;"
                        "word-spacing:0.18em;letter-spacing:0.01em;"
                    )
                    ui.label("LexMesh — AI Compliance Engine").style(
                        "font-size:0.9rem;font-weight:600;color:#647269;"
                    )

            ui.label("Effective Date: September 2026 · Applies to lexmesh.onrender.com").style(
                "font-size:0.82rem;color:#8a9e8f;margin-top:6px;"
            )

        # ── Critical Disclaimer Banner ────────────────────────────────────
        with ui.row().classes("w-full max-w-3xl items-start gap-3 p-4 rounded-xl mb-4").style(
            "background:#fef9ec;border:2px solid #e8b84b;border-radius:16px;"
        ):
            lucide_icon("triangle-alert", size=22, class_name="", extra_style="color:#b45339;flex-shrink:0;margin-top:2px;")
            ui.html(
                '<p style="color:#7a4a1a;font-size:0.93rem;line-height:1.65;margin:0;">'
                '<strong>Important Legal Notice:</strong> LexMesh provides automated compliance assessments '
                'for <strong>informational and audit preparation purposes only</strong>. '
                'Audit results generated by LexMesh <strong>do not constitute legal advice</strong> and '
                'do not substitute for formal review by qualified legal counsel or a licensed compliance professional. '
                'All regulatory and legal decisions must be independently verified by your legal team.'
                '</p>'
            )

        # ── Content Card ────────────────────────────────────────────────────
        with ui.card().classes("w-full max-w-3xl shadow-lg").style(
            "border-radius:20px;border:2px solid #ddd8cc;"
            "background:#fdfcf9;padding:40px;"
        ):

            def section(icon_name: str, heading: str, body: str):
                with ui.column().classes("w-full gap-2 mb-8"):
                    with ui.row().classes("items-center gap-2"):
                        lucide_icon(icon_name, size=20, class_name="", extra_style="color:#4e795d;")
                        ui.label(heading).style(
                            "font-size:1.1rem;font-weight:800;color:#1b3825;"
                        )
                    ui.separator().style("border-color:#e8e3d8;")
                    ui.html(f'<p style="color:#3d4a42;line-height:1.75;font-size:0.95rem;">{body}</p>')

            section(
                "info",
                "1. Nature of the Service",
                "LexMesh is an automated, AI-powered compliance audit tool designed to assist organizations in reviewing their internal policy documents "
                "against statutory compliance frameworks including EU GDPR, US HIPAA, RBI Cyber Security Directives, and SOC 2 Type II. "
                "LexMesh is intended as a <strong>preliminary audit preparation aid</strong> and does not replace the judgment, advice, "
                "or review of qualified legal professionals, certified compliance auditors, or regulatory bodies.",
            )

            section(
                "alert-triangle",
                "2. No Legal Advice — Limitation of Liability",
                "The compliance scores, gap analyses, remediation plans, and all other outputs produced by LexMesh are generated by artificial intelligence "
                "and are provided for <strong>informational purposes only</strong>. "
                "LexMesh and its operators expressly disclaim any liability for any loss, penalty, regulatory action, or legal consequence "
                "arising from any reliance on outputs generated by this platform. "
                "Users are solely responsible for verifying all audit findings with qualified legal counsel before taking regulatory or compliance actions.",
            )

            section(
                "user",
                "3. Acceptable Use",
                "By using LexMesh, you agree to use the platform only for lawful purposes and only in relation to documents you are authorized to process. "
                "You must not upload documents containing data that would expose third-party individuals to privacy risks in violation of applicable law. "
                "You must not attempt to reverse-engineer, scrape, or exploit the platform's outputs for commercial redistribution without written permission.",
            )

            section(
                "lock",
                "4. Account Responsibility",
                "You are responsible for maintaining the confidentiality of your login credentials. "
                "You agree to notify LexMesh immediately upon becoming aware of any unauthorized use of your account. "
                "LexMesh reserves the right to suspend or terminate accounts found to be in violation of these Terms.",
            )

            section(
                "refresh-cw",
                "5. Service Availability & Changes",
                "LexMesh is provided on an 'as-is' and 'as-available' basis. We do not guarantee uninterrupted or error-free operation of the service. "
                "We reserve the right to modify, update, or discontinue any feature or aspect of the service at any time without prior notice. "
                "Continued use of the service after any modification constitutes acceptance of the updated Terms.",
            )

            section(
                "globe",
                "6. Governing Law",
                "These Terms are governed by and construed in accordance with applicable laws. "
                "Any disputes arising from your use of LexMesh shall be subject to the exclusive jurisdiction of courts in the applicable territory. "
                "If any provision of these Terms is found to be unenforceable, the remaining provisions shall remain in full force and effect.",
            )

            section(
                "mail",
                "7. Contact",
                "If you have any questions about these Terms, compliance concerns, or legal notices, please contact the LexMesh team directly "
                "at <a href='mailto:lexmesh.official@gmail.com' style='color:#4e795d;font-weight:700;text-decoration:underline;'>lexmesh.official@gmail.com</a>. "
                "We aim to respond to all inquiries within 5 business days.",
            )

        # ── Footer ───────────────────────────────────────────────────────────
        with ui.row().classes("w-full max-w-3xl items-center justify-center gap-4 mt-8"):
            ui.link("Privacy Policy", f"/privacy?from={from_page}").classes(
                "text-sm font-semibold text-emerald-700 hover:underline"
            )
            ui.label("·").style("color:#8a9e8f;")
            ui.label("© 2026 LexMesh. All rights reserved.").style(
                "font-size:0.82rem;color:#8a9e8f;"
            )
