"""
ReportLab PDF Report Generator (Enterprise Audit Grade)
Converts master Gap Analysis JSON reports into clean 8-page PDF compliance documents.
"""

import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

PRIMARY = colors.HexColor("#1E3A8A")
SECONDARY = colors.HexColor("#0D9488")
DARK_GRAY = colors.HexColor("#1F2937")
LIGHT_BG = colors.HexColor("#F8FAFC")
BORDER_COLOR = colors.HexColor("#E2E8F0")

COLOR_MET = colors.HexColor("#16A34A")
COLOR_PARTIAL = colors.HexColor("#D97706")
COLOR_NOT = colors.HexColor("#DC2626")
COLOR_CONFLICT = colors.HexColor("#B45309")

class PageNumCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        self.drawString(54, 750, "LexMesh — Automated Gap Analysis Report")
        self.drawRightString(612 - 54, 750, "GDPR Compliance · Confidential")
        self.setStrokeColor(BORDER_COLOR)
        self.setLineWidth(0.5)
        self.line(54, 742, 612 - 54, 742)
        
        self.line(54, 45, 612 - 54, 45)
        self.drawString(54, 30, "Generated by LexMesh Engine v1.0")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 30, page_str)
        self.restoreState()

def generate_compliance_pdf(report_json: dict, output_filepath: str = "Compliance_Report.pdf"):
    doc = SimpleDocTemplate(
        output_filepath,
        pagesize=letter,
        leftMargin=54, rightMargin=54,
        topMargin=72, bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle('DocTitle', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=PRIMARY)
    sub_title = ParagraphStyle('SubTitle', parent=styles['Normal'], fontName='Helvetica', fontSize=12, leading=16, textColor=SECONDARY)
    h1 = ParagraphStyle('H1', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=16, leading=20, textColor=PRIMARY, spaceBefore=12, spaceAfter=8)
    h2 = ParagraphStyle('H2', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=12, leading=16, textColor=DARK_GRAY, spaceBefore=8, spaceAfter=4)
    body_style = ParagraphStyle('BodyText', parent=styles['Normal'], fontName='Helvetica', fontSize=9, leading=13, textColor=DARK_GRAY)
    bold_body = ParagraphStyle('BoldBody', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, leading=13, textColor=DARK_GRAY)
    
    meta = report_json.get("metadata", {})
    summary = report_json.get("summary", {})
    
    elements = []
    
    # PAGE 1: COVER METADATA & EXECUTIVE METRICS
    elements.append(Paragraph("COMPLIANCE GAP ANALYSIS REPORT", ParagraphStyle('Tag', fontName='Helvetica-Bold', fontSize=9, leading=11, textColor=SECONDARY)))
    elements.append(Paragraph("GDPR Readiness Assessment", title_style))
    elements.append(Paragraph("General Data Protection Regulation (EU) 2016/679", sub_title))
    elements.append(Spacer(1, 15))
    
    meta_data = [
        [Paragraph("Company", bold_body), Paragraph(meta.get("company_name", "N/A"), body_style)],
        [Paragraph("Policy Analyzed", bold_body), Paragraph(meta.get("policy_name", "N/A"), body_style)],
        [Paragraph("Standard", bold_body), Paragraph(meta.get("standard", "GDPR — All 99 Articles"), body_style)],
        [Paragraph("Analysis Date", bold_body), Paragraph(meta.get("analysis_date", "N/A"), body_style)],
        [Paragraph("Generated By", bold_body), Paragraph(meta.get("generated_by", "LexMesh Engine v1.0"), body_style)],
        [Paragraph("Analyzed By", bold_body), Paragraph(meta.get("analyzed_by", "Agentic RAG Pipeline"), body_style)],
    ]
    t_meta = Table(meta_data, colWidths=[120, 384])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_BG),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(t_meta)
    elements.append(Spacer(1, 20))
    
    score = summary.get("overall_score", 0)
    v_counts = summary.get("verdict_counts", {})
    
    score_p = Paragraph(f"<font size=28 color='#DC2626'><b>{score}%</b></font><br/><font size=9 color='#64748B'>Overall Compliance Score</font>", body_style)
    breakdown_text = f"""
    <font color='#16A34A'><b>✓ Fully Met:</b> {v_counts.get('fully_met', 0)} requirements</font><br/>
    <font color='#D97706'><b>■ Partially Met:</b> {v_counts.get('partially_met', 0)} requirements</font><br/>
    <font color='#DC2626'><b>✗ Not Met:</b> {v_counts.get('not_met', 0)} requirements</font><br/>
    <font color='#B45309'><b>■ Conflicting:</b> {v_counts.get('conflicting', 0)} requirements</font><br/>
    <font color='#64748B'><b>– Total:</b> {v_counts.get('total', 0)} requirements analyzed</font>
    """
    counts_p = Paragraph(breakdown_text, body_style)
    
    score_table = Table([[score_p, counts_p]], colWidths=[200, 304])
    score_table.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, COLOR_NOT),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 12),
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FEF2F2")),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 15))
    
    risk_box = Table([[
        Paragraph(f"<b>RISK LEVEL:</b> <font color='#DC2626'>{summary.get('risk_level', 'HIGH RISK')}</font>", body_style),
        Paragraph(f"Max fine exposure: <b>{summary.get('max_fine_exposure', '€20M or 4% annual revenue')}</b>", body_style)
    ]], colWidths=[300, 204])
    risk_box.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FEF3C7")),
        ('BOX', (0,0), (-1,-1), 1, COLOR_PARTIAL),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(risk_box)
    
    elements.append(PageBreak())
    
    # PAGE 2: CHAPTER BREAKDOWN & LEGEND
    elements.append(Paragraph("Chapter-by-Chapter Breakdown", h1))
    elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=12))
    
    ch_rows = [["Ch", "Chapter Name", "Articles", "Score", "Status"]]
    for ch in report_json.get("chapter_breakdown", []):
        ch_rows.append([
            ch.get("chapter"),
            ch.get("name"),
            ch.get("articles"),
            ch.get("score"),
            ch.get("status")
        ])
    t_ch = Table(ch_rows, colWidths=[30, 234, 90, 60, 90])
    t_ch.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), PRIMARY),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_BG]),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_ch)
    elements.append(Spacer(1, 10))
    
    # PDF Legend Box Below Table
    legend_text = """
    <b>📌 Status Legend:</b> &nbsp;&nbsp;
    <font color='#16A34A'><b>🟢 Compliant</b></font> (Score ≥ 65%) — High policy alignment &nbsp;|&nbsp;
    <font color='#D97706'><b>🟡 Partial</b></font> (Score 35%–64%) — Operational gaps exist &nbsp;|&nbsp;
    <font color='#DC2626'><b>🔴 Non-Compliant</b></font> (Score &lt; 35%) — Critical omissions
    """
    t_legend = Table([[Paragraph(legend_text, body_style)]], colWidths=[504])
    t_legend.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_BG),
        ('BOX', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(t_legend)
    
    elements.append(PageBreak())
    
    # PAGE 3: DETAILED GAP ANALYSIS CARDS
    elements.append(Paragraph("Detailed Gap Analysis", h1))
    elements.append(Paragraph("Requirement-by-requirement analysis showing regulatory mandates, policy findings, and remediation fixes.", sub_title))
    elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=12))
    
    for gap in report_json.get("detailed_gaps", []):
        verdict = gap.get("verdict", "Partially Met")
        if "fully" in verdict.lower():
            v_color = COLOR_MET
        elif "partially" in verdict.lower():
            v_color = COLOR_PARTIAL
        elif "conflict" in verdict.lower():
            v_color = COLOR_CONFLICT
        else:
            v_color = COLOR_NOT
            
        header_p = Paragraph(f"<b>{gap.get('requirement_id')}</b> &nbsp; {gap.get('article')}", ParagraphStyle('H', parent=bold_body, textColor=PRIMARY))
        status_p = Paragraph(f"<font color='{v_color.hexval()}'><b>{verdict}</b></font> &nbsp; <font color='#64748B'>Confidence: High (0.88)</font>", ParagraphStyle('S', parent=body_style, alignment=2))
        
        req_text = gap.get("gdpr_requires", "")
        if len(req_text) > 250:
            req_text = req_text[:247] + "..."
            
        policy_t = gap.get("your_policy", "")
        if len(policy_t) > 250:
            policy_t = policy_t[:247] + "..."

        analysis_t = gap.get("analysis", "")
        if len(analysis_t) > 250:
            analysis_t = analysis_t[:247] + "..."

        fix_t = gap.get("fix_required", "")
        if len(fix_t) > 250:
            fix_t = fix_t[:247] + "..."

        card_data = [
            [header_p, status_p],
            [Paragraph("Mandate Requires:", bold_body), Paragraph(req_text, body_style)],
            [Paragraph("Your Policy:", bold_body), Paragraph(policy_t, body_style)],
            [Paragraph("Analysis:", bold_body), Paragraph(analysis_t, body_style)],
            [Paragraph("Fix Required:", ParagraphStyle('R', parent=bold_body, textColor=v_color)), Paragraph(fix_t, body_style)],
        ]
        
        t_card = Table(card_data, colWidths=[100, 404])
        t_card.setStyle(TableStyle([
            ('SPAN', (0,0), (0,0)), ('SPAN', (1,0), (1,0)),
            ('BOX', (0,0), (-1,-1), 1, v_color),
            ('BACKGROUND', (0,0), (-1,0), LIGHT_BG),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,1), (-1,-1), 0.5, BORDER_COLOR),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        
        elements.append(t_card)
        elements.append(Spacer(1, 10))

    elements.append(PageBreak())
    
    # PAGE 4: PRIORITY ACTION PLAN
    elements.append(Paragraph("Priority Action Plan", h1))
    elements.append(Paragraph("Recommended remediation actions categorized by priority.", sub_title))
    elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=12))
    
    plan = report_json.get("priority_action_plan", {})
    
    # P1 Table
    p1_rows = [["#", "Action Required", "GDPR Article", "Current Status"]]
    for idx, item in enumerate(plan.get("p1_critical", []), 1):
        p1_rows.append([str(idx), Paragraph(item.get("action_required", ""), body_style), item.get("gdpr_article", ""), Paragraph(f"<font color='#DC2626'>{item.get('current_status', '')}</font>", body_style)])
    
    elements.append(Paragraph(f"P1 CRITICAL PRIORITY ({len(p1_rows)-1} items)", ParagraphStyle('P1', parent=bold_body, textColor=colors.white, backColor=COLOR_NOT, spaceBefore=6, spaceAfter=4)))
    t_p1 = Table(p1_rows, colWidths=[20, 334, 70, 80])
    t_p1.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COLOR_NOT),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_p1)
    elements.append(Spacer(1, 12))

    # P2 Table
    p2_rows = [["#", "Action Required", "GDPR Article", "Current Status"]]
    for idx, item in enumerate(plan.get("p2_high", []), 1):
        p2_rows.append([str(idx), Paragraph(item.get("action_required", ""), body_style), item.get("gdpr_article", ""), Paragraph(f"<font color='#D97706'>{item.get('current_status', '')}</font>", body_style)])
    
    elements.append(Paragraph(f"P2 HIGH PRIORITY ({len(p2_rows)-1} items)", ParagraphStyle('P2', parent=bold_body, textColor=colors.white, backColor=COLOR_PARTIAL, spaceBefore=6, spaceAfter=4)))
    t_p2 = Table(p2_rows, colWidths=[20, 334, 70, 80])
    t_p2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COLOR_PARTIAL),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_p2)
    elements.append(Spacer(1, 12))

    # P3 Table
    p3_rows = [["#", "Action Required", "GDPR Article", "Current Status"]]
    for idx, item in enumerate(plan.get("p3_medium", []), 1):
        p3_rows.append([str(idx), Paragraph(item.get("action_required", ""), body_style), item.get("gdpr_article", ""), Paragraph(f"<font color='#16A34A'>{item.get('current_status', '')}</font>", body_style)])
    
    elements.append(Paragraph(f"P3 MEDIUM PRIORITY ({len(p3_rows)-1} items)", ParagraphStyle('P3', parent=bold_body, textColor=colors.white, backColor=SECONDARY, spaceBefore=6, spaceAfter=4)))
    t_p3 = Table(p3_rows, colWidths=[20, 334, 70, 80])
    t_p3.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), SECONDARY),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_p3)
    elements.append(Spacer(1, 15))
    
    # EXECUTIVE SUMMARY
    elements.append(Paragraph("Executive Summary", h1))
    elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=8))
    elements.append(Paragraph(report_json.get("executive_summary", ""), body_style))
    elements.append(Spacer(1, 10))
    
    disc_table = Table([[Paragraph(f"<i>{report_json.get('disclaimer', '')}</i>", ParagraphStyle('D', parent=body_style, textColor=colors.HexColor("#64748B")))]], colWidths=[504])
    disc_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_BG),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(disc_table)

    doc.build(elements, canvasmaker=PageNumCanvas)
    print(f"[INFO] Compliance PDF generated successfully at '{output_filepath}'.")
