"""
ReportLab PDF Report Generator (Enterprise Multi-Framework Audit Grade)
Converts master Gap Analysis JSON reports into clean, comprehensive PDF compliance documents.
"""

import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

PRIMARY = colors.HexColor("#23382B")
SECONDARY = colors.HexColor("#4E795D")
DARK_GRAY = colors.HexColor("#1B2721")
LIGHT_BG = colors.HexColor("#F5F2EB")
BORDER_COLOR = colors.HexColor("#D4CBC0")

COLOR_MET = colors.HexColor("#3B6349")
COLOR_PARTIAL = colors.HexColor("#B45339")
COLOR_NOT = colors.HexColor("#9E3232")
COLOR_CONFLICT = colors.HexColor("#B45339")

class PageNumCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        self.drawString(54, 750, "LexMesh — Multi-Framework Compliance Audit Report")
        self.drawRightString(612 - 54, 750, "EU GDPR · US HIPAA · RBI Cyber · SOC 2 · Confidential")
        self.setStrokeColor(BORDER_COLOR)
        self.setLineWidth(0.5)
        self.line(54, 742, 612 - 54, 742)
        
        self.line(54, 45, 612 - 54, 45)
        self.drawString(54, 30, "Generated by LexMesh Multi-Framework Engine v2.0")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 30, page_str)
        self.restoreState()

def generate_compliance_pdf(report_json: dict, output_filepath: str = "Compliance_Report.pdf"):
    doc = SimpleDocTemplate(
        output_filepath,
        pagesize=letter,
        leftMargin=54, rightMargin=54,
        topMargin=72, bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle('DocTitle', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=20, leading=24, textColor=PRIMARY)
    sub_title = ParagraphStyle('SubTitle', parent=styles['Normal'], fontName='Helvetica', fontSize=11, leading=15, textColor=SECONDARY)
    h1 = ParagraphStyle('H1', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=14, leading=18, textColor=PRIMARY, spaceBefore=12, spaceAfter=6)
    h2 = ParagraphStyle('H2', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=11, leading=15, textColor=DARK_GRAY, spaceBefore=8, spaceAfter=4)
    body_style = ParagraphStyle('BodyText', parent=styles['Normal'], fontName='Helvetica', fontSize=8.5, leading=12, textColor=DARK_GRAY)
    bold_body = ParagraphStyle('BoldBody', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8.5, leading=12, textColor=DARK_GRAY)
    
    meta = report_json.get("metadata", {})
    summary = report_json.get("summary", {})
    fw_summaries = summary.get("framework_summaries", {})
    
    elements = []
    
    # PAGE 1: COVER METADATA & UNIFIED SCORE SUMMARY
    elements.append(Paragraph("MULTI-FRAMEWORK COMPLIANCE AUDIT REPORT", ParagraphStyle('Tag', fontName='Helvetica-Bold', fontSize=9, leading=11, textColor=SECONDARY)))
    elements.append(Paragraph("Enterprise Policy Gap Analysis", title_style))
    elements.append(Paragraph("EU GDPR · US HIPAA · RBI Cyber Framework · SOC 2 Type II", sub_title))
    elements.append(Spacer(1, 10))
    
    compliances = meta.get("compliances_analyzed", [])
    if not compliances:
        compliances = ["EU GDPR", "US HIPAA", "RBI Cyber Framework", "SOC 2 Type II"]
    compliances_str = ", ".join(compliances)

    meta_data = [
        [Paragraph("Organization", bold_body), Paragraph(meta.get("company_name", "N/A"), body_style)],
        [Paragraph("Policy Analyzed", bold_body), Paragraph(meta.get("policy_name", "N/A"), body_style)],
        [Paragraph("Compliances Evaluated", bold_body), Paragraph(compliances_str, body_style)],
        [Paragraph("Analysis Date", bold_body), Paragraph(meta.get("analysis_date", "N/A"), body_style)],
        [Paragraph("Audit Engine", bold_body), Paragraph(meta.get("generated_by", "LexMesh Multi-Framework Engine v2.0"), body_style)],
    ]
    t_meta = Table(meta_data, colWidths=[120, 384])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_BG),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_meta)
    elements.append(Spacer(1, 12))
    
    overall_score = summary.get("overall_score", 0)
    score_p = Paragraph(f"<font size=24 color='#23382B'><b>{overall_score}%</b></font><br/><font size=8.5 color='#647269'>Unified Overall Multi-Framework Score</font>", body_style)
    risk_p = Paragraph(f"<b>Overall Posture:</b> {summary.get('overall_risk', 'HIGH RISK')}<br/><font color='#647269'>Simultaneous RAG evaluation across all 4 regulatory frameworks.</font>", body_style)
    
    score_table = Table([[score_p, risk_p]], colWidths=[180, 324])
    score_table.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, PRIMARY),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 8),
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#E2EBE5")),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 12))

    # FRAMEWORK-BY-FRAMEWORK SUMMARY TABLE
    elements.append(Paragraph("Compliance Standard Score Breakdown", h1))
    fw_rows = [["Standard", "Score", "Risk Level", "Statutory Penalty / Audit Exposure"]]
    
    fw_labels = []
    if "gdpr" in fw_summaries: fw_labels.append(("gdpr", "EU GDPR"))
    if "hipaa" in fw_summaries: fw_labels.append(("hipaa", "US HIPAA"))
    if "rbi" in fw_summaries: fw_labels.append(("rbi", "RBI Cyber Framework"))
    if "soc2" in fw_summaries: fw_labels.append(("soc2", "SOC 2 Type II"))
    
    if not fw_labels:
        fw_labels = [("gdpr", "EU GDPR"), ("hipaa", "US HIPAA"), ("rbi", "RBI Cyber Framework"), ("soc2", "SOC 2 Type II")]
    
    for fw_key, label in fw_labels:
        s_data = fw_summaries.get(fw_key, {})
        fw_rows.append([
            Paragraph(f"<b>{label}</b>", body_style),
            f"{s_data.get('score', 0)}%",
            Paragraph(s_data.get("risk_level", "High Risk"), body_style),
            Paragraph(s_data.get("penalty_exposure", "Statutory Penalty"), body_style)
        ])
        
    t_fw = Table(fw_rows, colWidths=[120, 45, 130, 209])
    t_fw.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), PRIMARY),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_BG]),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_fw)
    
    # PAGE 2: POLICY DOMAIN BREAKDOWN
    elements.append(PageBreak())
    elements.append(Paragraph("Policy Domain Readiness Breakdown", h1))
    elements.append(Paragraph("Compliance readiness evaluated across 6 core enterprise policy domains.", sub_title))
    elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=8))
    
    active_fws_table = []
    if "gdpr" in fw_summaries: active_fws_table.append("gdpr")
    if "hipaa" in fw_summaries: active_fws_table.append("hipaa")
    if "rbi" in fw_summaries: active_fws_table.append("rbi")
    if "soc2" in fw_summaries: active_fws_table.append("soc2")
    if not active_fws_table:
        active_fws_table = ["gdpr", "hipaa", "rbi", "soc2"]

    fw_names_map = {
        "gdpr": "GDPR",
        "hipaa": "HIPAA",
        "rbi": "RBI",
        "soc2": "SOC 2"
    }

    headers = ["Policy Domain", "Readiness", "Status"] + [fw_names_map[fw] for fw in active_fws_table]
    dom_rows = [headers]

    for dom in report_json.get("policy_domain_breakdown", []):
        fw_sc = dom.get("framework_scores", {})
        row = [
            Paragraph(f"<b>{dom.get('domain_title')}</b>", body_style),
            dom.get("score"),
            dom.get("status")
        ]
        for fw in active_fws_table:
            row.append(f"{fw_sc.get(fw, 0)}%")
        dom_rows.append(row)

    # Split the remaining 230 points of table width (534 total width) equally among active frameworks
    fw_width = 230.0 / len(active_fws_table)
    widths = [174.0, 55.0, 75.0] + [fw_width] * len(active_fws_table)

    t_dom = Table(dom_rows, colWidths=widths)
    t_dom.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), PRIMARY),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_BG]),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_dom)
    elements.append(Spacer(1, 15))
    
    # PAGE 3: DETAILED POLICY GAPS FOR ALL 4 COMPLIANCE STANDARDS
    elements.append(Paragraph("Detailed Policy Gap Analysis — Multi-Framework Audit Cards", h1))
    elements.append(Paragraph("Requirement-by-requirement audit findings with specific policy fixes across all compliances.", sub_title))
    elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=8))
    
    all_gaps = report_json.get("all_gaps_flat", report_json.get("detailed_gaps", []))
    
    # Group gaps by framework to ensure every standard is explicitly represented
    gaps_by_fw = {"gdpr": [], "hipaa": [], "rbi": [], "soc2": []}
    for gap in all_gaps:
        fw = gap.get("framework", "gdpr").lower()
        if fw in gaps_by_fw:
            gaps_by_fw[fw].append(gap)

    fw_display_names = [
        ("gdpr", "EU GDPR — Detailed Audit Findings & Policy Fixes"),
        ("hipaa", "US HIPAA — Detailed Audit Findings & Policy Fixes"),
        ("rbi", "RBI Cyber Framework — Detailed Audit Findings & Policy Fixes"),
        ("soc2", "SOC 2 Type II — Detailed Audit Findings & Policy Fixes")
    ]

    for fw_key, fw_heading in fw_display_names:
        fw_gaps = gaps_by_fw.get(fw_key, [])
        if not fw_gaps:
            continue
            
        elements.append(Paragraph(fw_heading, h2))
        
        # Render top 5 key gaps for each framework
        for gap in fw_gaps[:5]:
            verdict = gap.get("verdict", "Partially Met")
            if "fully" in verdict.lower():
                v_color = COLOR_MET
            elif "partially" in verdict.lower():
                v_color = COLOR_PARTIAL
            elif "conflict" in verdict.lower():
                v_color = COLOR_CONFLICT
            else:
                v_color = COLOR_NOT
                
            fw_tag = gap.get("framework", "gdpr").upper()
            header_p = Paragraph(f"<b>[{fw_tag}] {gap.get('requirement_id')}</b> &nbsp; {gap.get('article')}", ParagraphStyle('H', parent=bold_body, textColor=PRIMARY))
            status_p = Paragraph(f"<font color='{v_color.hexval()}'><b>{verdict}</b></font>", ParagraphStyle('S', parent=body_style, alignment=2))
            
            req_text = gap.get("requirement_mandate") or gap.get("gdpr_requires", "")
            if len(req_text) > 170:
                req_text = req_text[:167] + "..."
                
            policy_t = gap.get("your_policy", "")
            if len(policy_t) > 170:
                policy_t = policy_t[:167] + "..."

            fix_t = gap.get("fix_required", "")
            if len(fix_t) > 170:
                fix_t = fix_t[:167] + "..."

            card_data = [
                [header_p, status_p],
                [Paragraph("Mandate:", bold_body), Paragraph(req_text, body_style)],
                [Paragraph("Policy Citation:", bold_body), Paragraph(policy_t, body_style)],
                [Paragraph("Fix Required:", ParagraphStyle('R', parent=bold_body, textColor=v_color)), Paragraph(fix_t, body_style)],
            ]
            
            t_card = Table(card_data, colWidths=[90, 414])
            t_card.setStyle(TableStyle([
                ('SPAN', (0,0), (0,0)), ('SPAN', (1,0), (1,0)),
                ('BOX', (0,0), (-1,-1), 1, v_color),
                ('BACKGROUND', (0,0), (-1,0), LIGHT_BG),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('GRID', (0,1), (-1,-1), 0.5, BORDER_COLOR),
                ('PADDING', (0,0), (-1,-1), 4),
            ]))
            
            elements.append(t_card)
            elements.append(Spacer(1, 6))

    # PAGE 4: MULTI-FRAMEWORK PRIORITY ACTION PLAN
    elements.append(PageBreak())
    elements.append(Paragraph("Policy Remediation Action Plan (All Compliance Standards)", h1))
    elements.append(Paragraph("Prioritized remediation items across EU GDPR, US HIPAA, RBI Cyber Framework, and SOC 2 Type II.", sub_title))
    elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=8))
    
    plan = report_json.get("priority_action_plan", {})
    
    # P1 Table
    p1_items = plan.get("p1_critical", [])
    if p1_items:
        p1_rows = [["#", "Policy Domain", "Regulation", "Action Required", "Status"]]
        for idx, item in enumerate(p1_items, 1):
            dom_t = item.get("Policy Domain") or item.get("policy_domain", "")
            fw_t = item.get("Framework Compliance") or item.get("Framework compliance") or item.get("Framework Standard") or item.get("framework_tag", item.get("gdpr_article", ""))
            act_t = item.get("Action Required") or item.get("action_required", "")
            stat_t = item.get("Current Status") or item.get("current_status", "")
            p1_rows.append([
                str(idx),
                Paragraph(dom_t, body_style),
                Paragraph(fw_t, body_style),
                Paragraph(act_t, body_style),
                Paragraph(f"<font color='#DC2626'>{stat_t}</font>", body_style)
            ])
        
        elements.append(Paragraph(f"P1 CRITICAL PRIORITY ({len(p1_items)} items)", ParagraphStyle('P1', parent=bold_body, textColor=colors.white, backColor=COLOR_NOT, spaceBefore=4, spaceAfter=4)))
        t_p1 = Table(p1_rows, colWidths=[20, 105, 110, 199, 70])
        t_p1.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), COLOR_NOT),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        elements.append(t_p1)
        elements.append(Spacer(1, 10))

    # P2 Table
    p2_items = plan.get("p2_high", [])
    if p2_items:
        p2_rows = [["#", "Policy Domain", "Regulation", "Action Required", "Status"]]
        for idx, item in enumerate(p2_items, 1):
            dom_t = item.get("Policy Domain") or item.get("policy_domain", "")
            fw_t = item.get("Framework Compliance") or item.get("Framework compliance") or item.get("Framework Standard") or item.get("framework_tag", item.get("gdpr_article", ""))
            act_t = item.get("Action Required") or item.get("action_required", "")
            stat_t = item.get("Current Status") or item.get("current_status", "")
            p2_rows.append([
                str(idx),
                Paragraph(dom_t, body_style),
                Paragraph(fw_t, body_style),
                Paragraph(act_t, body_style),
                Paragraph(f"<font color='#B45339'>{stat_t}</font>", body_style)
            ])
        
        elements.append(Paragraph(f"P2 HIGH PRIORITY ({len(p2_items)} items)", ParagraphStyle('P2', parent=bold_body, textColor=colors.white, backColor=COLOR_PARTIAL, spaceBefore=4, spaceAfter=4)))
        t_p2 = Table(p2_rows, colWidths=[20, 105, 110, 199, 70])
        t_p2.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), COLOR_PARTIAL),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        elements.append(t_p2)
        elements.append(Spacer(1, 10))

    # P3 Table
    p3_items = plan.get("p3_medium", [])
    if p3_items:
        p3_rows = [["#", "Policy Domain", "Regulation", "Action Required", "Status"]]
        for idx, item in enumerate(p3_items, 1):
            dom_t = item.get("Policy Domain") or item.get("policy_domain", "")
            fw_t = item.get("Framework Compliance") or item.get("Framework compliance") or item.get("Framework Standard") or item.get("framework_tag", item.get("gdpr_article", ""))
            act_t = item.get("Action Required") or item.get("action_required", "")
            stat_t = item.get("Current Status") or item.get("current_status", "")
            p3_rows.append([
                str(idx),
                Paragraph(dom_t, body_style),
                Paragraph(fw_t, body_style),
                Paragraph(act_t, body_style),
                Paragraph(f"<font color='#3B6349'>{stat_t}</font>", body_style)
            ])
        
        elements.append(Paragraph(f"P3 MEDIUM PRIORITY ({len(p3_items)} items)", ParagraphStyle('P3', parent=bold_body, textColor=colors.white, backColor=SECONDARY, spaceBefore=4, spaceAfter=4)))
        t_p3 = Table(p3_rows, colWidths=[20, 105, 110, 199, 70])
        t_p3.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), SECONDARY),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        elements.append(t_p3)
        elements.append(Spacer(1, 12))

    # COMPLIANT AREAS SECTION
    compliant_items = report_json.get("compliant_areas", [])
    if compliant_items:
        elements.append(Paragraph("Compliant Areas (Passed Requirements)", h1))
        elements.append(Paragraph("Statutory requirements successfully met by operational controls in the policy document.", sub_title))
        elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=8))
        
        comp_rows = [["#", "Policy Domain", "Regulation", "Citation", "Status"]]
        for idx, item in enumerate(compliant_items, 1):
            dom_t = item.get("Policy Domain") or item.get("policy_domain", "")
            fw_t = item.get("Framework Standard") or item.get("framework_tag", "")
            cit_t = item.get("Requirement Citation") or item.get("article", "")
            stat_t = item.get("Current Status") or "Fully Compliant"
            comp_rows.append([
                str(idx),
                Paragraph(dom_t, body_style),
                Paragraph(fw_t, body_style),
                Paragraph(cit_t, body_style),
                Paragraph(f"<font color='#3B6349'><b>{stat_t}</b></font>", body_style)
            ])
        
        elements.append(Paragraph(f"COMPLIANT AREAS ({len(compliant_items)} items)", ParagraphStyle('COMP', parent=bold_body, textColor=colors.white, backColor=COLOR_MET, spaceBefore=4, spaceAfter=4)))
        t_comp = Table(comp_rows, colWidths=[20, 135, 130, 149, 70])
        t_comp.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), COLOR_MET),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        elements.append(t_comp)
        elements.append(Spacer(1, 12))
    
    # EXECUTIVE SUMMARY & DISCLAIMER
    elements.append(Paragraph("Executive Summary", h1))
    elements.append(HRFlowable(width="100%", thickness=1, color=PRIMARY, spaceAfter=6))
    elements.append(Paragraph(report_json.get("executive_summary", ""), body_style))
    elements.append(Spacer(1, 10))
    
    disc_table = Table([[Paragraph(f"<i>{report_json.get('disclaimer', '')}</i>", ParagraphStyle('D', parent=body_style, textColor=colors.HexColor("#64748B")))]], colWidths=[504])
    disc_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_BG),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(disc_table)

    doc.build(elements, canvasmaker=PageNumCanvas)
    print(f"[INFO] Compliance PDF generated successfully at '{output_filepath}'.")
