"""
ReportLab PDF Generator for ComplianceIQ
Converts master Gap Analysis JSON report into an audit-ready multi-page PDF document
matching the exact visual layout of OutputReport_GDPRCompliance.pdf.
"""

import os
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (Pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "ComplianceIQ — Automated Gap Analysis Report")
            self.drawRightString(612 - 54, 750, "GDPR Compliance · Confidential")
            self.setStrokeColor(colors.HexColor("#3B82F6"))
            self.setLineWidth(1)
            self.line(54, 742, 612 - 54, 742)
            
        # Footer (All pages)
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 45, 612 - 54, 45)
        
        self.drawString(54, 30, "Generated by LexMesh Engine")
        page_str = f"Page {self._pageNumber}"
        self.drawRightString(612 - 54, 30, page_str)
        self.restoreState()

def generate_compliance_pdf(report_json: dict, output_pdf_path: str) -> str:
    """
    Renders master Gap Analysis JSON report into a multi-page PDF document.
    """
    meta = report_json.get("metadata", {})
    summary = report_json.get("summary", {})
    ch_breakdown = report_json.get("chapter_breakdown", [])
    gaps = report_json.get("detailed_gaps", [])
    action_plan = report_json.get("priority_action_plan", {})
    exec_summary = report_json.get("executive_summary", "")
    disclaimer = report_json.get("disclaimer", "")

    doc = SimpleDocTemplate(
        output_pdf_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=64,
        bottomMargin=64
    )

    styles = getSampleStyleSheet()

    # Color Palette
    c_blue = colors.HexColor("#2563EB")
    c_dark = colors.HexColor("#1E293B")
    c_red = colors.HexColor("#DC2626")
    c_orange = colors.HexColor("#D97706")
    c_green = colors.HexColor("#16A34A")
    c_light_red = colors.HexColor("#FEF2F2")
    c_light_bg = colors.HexColor("#F8FAFC")

    # Typography Styles
    title_style = ParagraphStyle('RTitle', fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=c_dark, spaceAfter=4)
    subtitle_style = ParagraphStyle('RSubTitle', fontName='Helvetica', fontSize=12, leading=15, textColor=c_blue, spaceAfter=15)
    h1_style = ParagraphStyle('RH1', fontName='Helvetica-Bold', fontSize=15, leading=18, textColor=c_dark, spaceBefore=12, spaceAfter=8)
    body_style = ParagraphStyle('RBody', fontName='Helvetica', fontSize=9, leading=13, textColor=c_dark)
    bold_body = ParagraphStyle('RBoldBody', fontName='Helvetica-Bold', fontSize=9, leading=13, textColor=c_dark)

    story = []

    # PAGE 1: COVER & METADATA & OVERALL SCORE
    story.append(Paragraph("COMPLIANCE GAP ANALYSIS REPORT", ParagraphStyle('SubHeader', fontName='Helvetica-Bold', fontSize=10, leading=12, textColor=c_blue)))
    story.append(Paragraph("GDPR Readiness Assessment", title_style))
    story.append(Paragraph("General Data Protection Regulation (EU) 2016/679", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=c_blue, spaceBefore=2, spaceAfter=15))

    # Metadata Table
    meta_data = [
        [Paragraph("Company", bold_body), Paragraph(meta.get("company_name", "N/A"), body_style)],
        [Paragraph("Policy Analyzed", bold_body), Paragraph(meta.get("policy_name", "N/A"), body_style)],
        [Paragraph("Standard", bold_body), Paragraph(meta.get("standard", "GDPR — All 99 Articles"), body_style)],
        [Paragraph("Analysis Date", bold_body), Paragraph(meta.get("analysis_date", "N/A"), body_style)],
        [Paragraph("Generated By", bold_body), Paragraph(meta.get("generated_by", "LexMesh Engine v1.0"), body_style)],
        [Paragraph("Analyzed By", bold_body), Paragraph(meta.get("analyzed_by", "Agentic RAG Pipeline"), body_style)],
    ]
    t_meta = Table(meta_data, colWidths=[120, 384])
    t_meta.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, c_light_bg]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 20))

    # Overall Compliance Score Box
    counts = summary.get("verdict_counts", {})
    score_p = Paragraph(f"<font size=36 color='{c_red.hexval()}'><b>{summary.get('overall_score', 0)}%</b></font><br/><font size=9 color='#64748B'>Overall Compliance Score</font>", body_style)
    counts_text = (
        f"<font color='{c_green.hexval()}'><b>✓ Fully Met:</b> {counts.get('fully_met', 0)} requirements</font><br/>"
        f"<font color='{c_orange.hexval()}'><b>■ Partially Met:</b> {counts.get('partially_met', 0)} requirements</font><br/>"
        f"<font color='{c_red.hexval()}'><b>✗ Not Met:</b> {counts.get('not_met', 0)} requirements</font><br/>"
        f"<font color='{c_orange.hexval()}'><b>■ Conflicting:</b> {counts.get('conflicting', 0)} requirements</font><br/>"
        f"<b>– Total:</b> {counts.get('total', 0)} requirements analyzed"
    )
    counts_p = Paragraph(counts_text, ParagraphStyle('CountsP', fontName='Helvetica', fontSize=9, leading=14))
    
    t_score = Table([[score_p, counts_p]], colWidths=[200, 304])
    t_score.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), c_light_red),
        ('BOX', (0, 0), (-1, -1), 1, c_red),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('LEFTPADDING', (0, 0), (-1, -1), 15),
    ]))
    story.append(t_score)
    story.append(Spacer(1, 15))

    # Risk Box
    risk_p = Paragraph(f"<b>RISK LEVEL:</b> <font color='{c_red.hexval()}'><b>{summary.get('risk_level', 'HIGH RISK')}</b></font>", body_style)
    fine_p = Paragraph(f"Max fine exposure: {summary.get('max_fine_exposure', '€20M or 4% revenue')}", body_style)
    t_risk = Table([[risk_p, fine_p]], colWidths=[320, 184])
    t_risk.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#FEF3C7")),
        ('BOX', (0, 0), (-1, -1), 1, c_orange),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t_risk)
    story.append(PageBreak())

    # PAGE 2: CHAPTER-BY-CHAPTER BREAKDOWN
    story.append(Paragraph("Chapter-by-Chapter Breakdown", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=2, spaceAfter=10))

    ch_table_data = [[Paragraph("Ch", bold_body), Paragraph("Chapter Name", bold_body), Paragraph("Articles", bold_body), Paragraph("Score", bold_body), Paragraph("Status", bold_body)]]
    for ch in ch_breakdown:
        score_val = ch.get("score", 0)
        s_color = c_green if score_val >= 65 else (c_orange if score_val >= 40 else c_red)
        status_icon = ch.get("status", "✓")
        
        ch_table_data.append([
            Paragraph(ch.get("chapter", ""), body_style),
            Paragraph(ch.get("name", ""), body_style),
            Paragraph(ch.get("articles", ""), body_style),
            Paragraph(f"<font color='{s_color.hexval()}'><b>{score_val}%</b></font>", body_style),
            Paragraph(f"<font color='{s_color.hexval()}'><b>{status_icon}</b></font>", body_style),
        ])

    t_ch = Table(ch_table_data, colWidths=[30, 230, 100, 70, 74])
    t_ch.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_light_bg]),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t_ch)
    story.append(Spacer(1, 15))
    story.append(PageBreak())

    # PAGE 3-6: DETAILED GAP ANALYSIS CARDS
    story.append(Paragraph("Detailed Gap Analysis", h1_style))
    story.append(Paragraph("Requirement-by-requirement analysis showing regulatory mandates, policy findings, and remediation fixes.", body_style))
    story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=4, spaceAfter=12))

    for gap in gaps[:10]: # Top 10 critical gaps
        req_id = gap.get("requirement_id", "")
        article = gap.get("article", "")
        verdict = gap.get("verdict", "Partially Met")
        confidence = gap.get("confidence", "High (0.82)")
        
        v_color = c_green if "fully" in verdict.lower() else (c_orange if "partially" in verdict.lower() or "conflict" in verdict.lower() else c_red)
        
        header_text = f"<b>{req_id}</b> &nbsp;&nbsp; {article} &nbsp;&nbsp; <font color='{v_color.hexval()}'><b>■ {verdict}</b></font>"
        right_text = f"<font size=8 color='#64748B'>Confidence: {confidence}</font>"
        
        header_p = Paragraph(header_text, body_style)
        right_p = Paragraph(right_text, ParagraphStyle('RRight', alignment=2, fontName='Helvetica', fontSize=8))
        
        card_content = [
            [header_p, right_p],
            [Paragraph("<b>GDPR Requires:</b>", bold_body), Paragraph(gap.get("gdpr_requires", ""), body_style)],
            [Paragraph("<b>Your Policy:</b>", bold_body), Paragraph(gap.get("your_policy", ""), body_style)],
            [Paragraph("<b>Analysis:</b>", bold_body), Paragraph(gap.get("analysis", ""), body_style)],
            [Paragraph("<font color='#DC2626'><b>Fix Required:</b></font>", bold_body), Paragraph(gap.get("fix_required", ""), body_style)],
        ]
        
        t_card = Table(card_content, colWidths=[110, 394])
        t_card.setStyle(TableStyle([
            ('SPAN', (0, 0), (0, 0)),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#FEF2F2") if "not met" in verdict.lower() else colors.HexColor("#FFFBEB")),
            ('BOX', (0, 0), (-1, -1), 1, v_color),
            ('GRID', (0, 1), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(t_card)
        story.append(Spacer(1, 10))

    story.append(PageBreak())

    # PAGE 7: PRIORITY ACTION PLAN
    story.append(Paragraph("Priority Action Plan", h1_style))
    story.append(Paragraph("Recommended remediation actions categorized by priority.", body_style))
    story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=4, spaceAfter=10))

    for p_level, p_name, color_hex, items in [
        ("P1", "CRITICAL PRIORITY", "#DC2626", action_plan.get("p1_critical", [])),
        ("P2", "HIGH PRIORITY", "#D97706", action_plan.get("p2_high", [])),
        ("P3", "MEDIUM PRIORITY", "#0D9488", action_plan.get("p3_medium", [])),
    ]:
        if not items:
            continue
        header_table = Table([[Paragraph(f"<b>{p_level} &nbsp; {p_name}</b>", ParagraphStyle('PHeader', fontName='Helvetica-Bold', textColor=colors.white, fontSize=9)), Paragraph(f"<b>{len(items)} items</b>", ParagraphStyle('PRight', fontName='Helvetica-Bold', textColor=colors.white, fontSize=9, alignment=2))]], colWidths=[380, 124])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor(color_hex)),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(header_table)
        
        p_rows = [[Paragraph("#", bold_body), Paragraph("Action Required", bold_body), Paragraph("GDPR Article", bold_body), Paragraph("Current Status", bold_body)]]
        for idx, item in enumerate(items, 1):
            p_rows.append([
                Paragraph(str(idx), body_style),
                Paragraph(item.get("action_required", ""), body_style),
                Paragraph(item.get("gdpr_article", ""), body_style),
                Paragraph(f"<font color='{color_hex}'>{item.get('current_status', '')}</font>", body_style),
            ])
        t_plan = Table(p_rows, colWidths=[24, 250, 90, 140])
        t_plan.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_light_bg]),
            ('PADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(t_plan)
        story.append(Spacer(1, 12))

    story.append(PageBreak())

    # PAGE 8: EXECUTIVE SUMMARY & DISCLAIMER
    story.append(Paragraph("Executive Summary", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=4, spaceAfter=10))
    story.append(Paragraph(exec_summary, ParagraphStyle('ExecSummaryP', fontName='Helvetica', fontSize=10, leading=15, textColor=c_dark)))
    story.append(Spacer(1, 25))

    story.append(Paragraph(disclaimer, ParagraphStyle('DisclaimerP', fontName='Helvetica-Oblique', fontSize=8, leading=11, textColor=colors.HexColor("#64748B"), backColor=c_light_bg, borderPadding=8)))

    doc.build(story, canvasmaker=NumberedCanvas)
    print(f"[INFO] Compliance PDF report generated successfully at: {output_pdf_path}")
    return output_pdf_path

if __name__ == "__main__":
    # Test stub
    test_json_path = r"C:\Users\Admin\.gemini\antigravity-ide\brain\c5faa3e9-a1b3-44b7-9f5d-3671a9ebb9b8\scratch\sample_report.json"
    if os.path.exists(test_json_path):
        with open(test_json_path, 'r') as f:
            data = json.load(f)
            generate_compliance_pdf(data, "test_output.pdf")
